# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-25 06:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('speciality', models.CharField(choices=[('Cardiologist', 'Cardiologist'), ('Medicine', 'Medicine'), ('Dermatologist', 'Dermatologist'), ('Pediatrician', 'Pediatrician'), ('Gastroenterologist', 'Gastroenterologist'), ('Gynecologist', 'Gynecologist'), ('Neurologist', 'Neurologist'), ('Orthopedic', 'Orthopedic'), ('Psychiatrist', 'Psychiatrist'), ('Dentist', 'Dentist')], max_length=50)),
                ('health_issue', models.CharField(choices=[('chest pain', 'chest pain'), ('suffocation', 'suffocation'), ('stomachache', 'stomachache'), ('toothache', 'toothache'), ('fever', 'fever'), ('allergy', 'allergy'), ('std', 'std'), ('constipation', 'constipation'), ('diarrhea', 'diarrhea'), ('dysentery', 'dysentery'), ('ulcer', 'ulcer'), ('child disease', 'child disease'), ('gastric', 'gastric'), ('marital issues', 'marital issues'), ('headache', 'headache'), ('mental condition', 'mental condition'), ('broken bone', 'broken bone'), ('fracture', 'fracture'), ('stroke', 'stroke'), ('nervous problems', 'nervous problems'), ('seizure', 'seizure'), ('swallowing', 'swallowing')], max_length=50)),
                ('dp', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=500)),
                ('area', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('image', models.FileField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hms.Hospital'),
        ),
    ]
